apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dev-taco-cloud
  name: taco-cloud

template:
  spec:
    containers:
      - image: app-image
        imagePullPolicy: IfNotPresent
        name: taco-cloud