commonLabels:
  variant: development

commonAnnotations:
  description: Taco Cloud project
  source: kustomize
  team: sanacloud

namePrefix: staging-

bases:
  - ../../base

patchesStrategicMerge:
- replica_count.yaml
- delete_route.yaml