apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taco-cloud
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-taco-cloud'
      annotations:
        argocd-image-updater.argoproj.io/image-list: georgevazj/taco-cloud
        argocd-image-updater.argoproj.io/yourtool.update-strategy: latest
        # argocd-image-updater.argoproj.io/yourtool.allow-tags: regexp:^v1.0.0-[0-9a-zA-Z]+$
        argocd-image-updater.argoproj.io/yourtool.allow-tags: regexp:^[0-9a-zA-Z]+$
        argocd-image-updater.argoproj.io/write-back-method: declarative
    spec:
      project: default
      source:
        repoURL: https://github.com/georgevazj/taco-cloud-config
        targetRevision: main
        path: overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: taco-cloud
      syncPolicy:
        automated:
            prune: true
            selfHeal: true