apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taco-cloud-config
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-taco-cloud'
    spec:
      project: gitops-demo
      source:
        repoURL: https://github.com/georgevazj/taco-cloud-config.git
        targetRevision: main
        path: overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd