apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taco-cloud
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://sans1weuakssanaks001-dns-ae267f23.hcp.westeurope.azmk8s.io:443
  template:
    metadata:
      name: '{{cluster}}-taco-cloud'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd-image-updater.argoproj.io/image-list: front=docker.io/georgevazj/taco-cloud
        argocd-image-updater.argoproj.io/front.update-strategy: latest
        argocd-image-updater.argoproj.io/front.allow-tags: any
        argocd-image-updater.argoproj.io/front.kustomize.image-name: app-image
        argocd-image-updater.argoproj.io/write-back-method: git
    spec:
      project: default
      source:
        repoURL: https://github.com/georgevazj/taco-cloud-config
        targetRevision: main
        path: overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: taco-cloud
      syncPolicy:
        automated:
            prune: true
            selfHeal: true