apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taco-cloud-operator
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-taco-cloud'
    spec:
      project: default
      source:
        repoURL: https://github.com/georgevazj/taco-cloud-config
        targetRevision: main
        path: overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: taco-cloud
      syncPolicy:
        automated:
            prune: true
            selfHeal: true