apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- route.yaml
- secret.yaml
- service_account.yaml

labels:
- pairs:
    kind: front
    lang: spring
    project: taco-cloud
    region: westeurope

commonAnnotations:
  description: Taco Cloud project
  source: kustomize
  team: sanacloud

images:
- digest: sha256:7ca0cf7c255e5a2e618e54ec4e8caa60c052b85f06724a10102f48cca410898b
  name: app-image
  newName: docker.io/georgevazj/taco-cloud
