apiVersion: v1
kind: Role
metadata:
  name: taco-cloud-app
  namespace: taco-cloud
rules:
- apiGroups: [""]
  resources: ["pods", "pods/logs","services", "deployments", "replicasets", "configmaps", "secrets", "persistenvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list"]