# Hashicorp Vault secret
kind: Secret
apiVersion: v1
metadata:
  namespace: taco-cloud
  name: taco-cloud
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/supersecret"
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: <username>
  password: <password>
