apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dev-taco-cloud
  name: dev-taco-cloud
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: dev-taco-cloud
    deploymentconfig: dev-taco-cloud
